id: A0C22FF31
base_file: f16E8.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 20:49:21.844713
  last_modified_at: 2022-05-30 20:49:21.844722
